### ISSUE TITLE
Not working :(

### ISSUE THREAD

**Issue by emmu123** [JustArtiom/ArtiomsHosting-Bot#5]

**Comment by emmu123** [comment]
Bot not working only reacting to command :(
![ice_screenshot_20220505-203755](https://user-images.githubusercontent.com/89377181/166956837-c6c6b505-cf5e-47ac-bc49-64900953f2ee.png)

**Comment by Neodevils** [comment]
Panel is down for now.

**Comment by emmu123** [comment]
I not using artiom panel i using my panel but bot have some problem :(

**Comment by JustArtiom** [comment]
Better take it to discord in dms :)

**Comment by Neodevils** [comment]
> I not using artiom panel i using my panel but bot have some problem :(

That's literally same. And now it is fixed. Have a nice day 😊
